<?php
/**@var \Magento\Customer\Block\Account\AuthorizationLink $block */
?>
<div class="customer_links">
    <?php if (!$block->isLoggedIn()): ?>
        <div class="login_reg">
            <li><svg id="login_click" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
            </svg></li>
            <div class="login_mobi">
                <li><a href="<?php echo $block->getUrl('customer/account/login'); ?>">
                    <span><?php echo __('Login'); ?></span>
                </a></li>
                <li><a href="<?php echo $block->getUrl('customer/account/create'); ?>">
                    <span><?php echo __('Register'); ?></span>
                </a></li>
            </div>
            <div class="login_desktop">
                <li><a href="<?php echo $block->getUrl('customer/account/login'); ?>">
                    <span><?php echo __('Login'); ?></span>
                </a></li>
                <span id="or"><?php echo __('/'); ?></span>
                <li><a href="<?php echo $block->getUrl('customer/account/create'); ?>">
                    <span><?php echo __('Register'); ?></span>
                </a></li>
            </div>
        </div>
    <?php else:?>
        <a href="<?php echo $block->getUrl('customer/account'); ?>"> <?php echo __('My Account'); ?></a>
        <span id="or"><?php echo __('/'); ?></span>
        <a href="<?php echo $block->getUrl('customer/account/logout'); ?>"> <?php echo __('Logout'); ?></a>
    <?php endif; ?>
    <div class="wishlist">
        <a href="<?php echo $block->getUrl('wishlist/index/index'); ?>">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
            </svg>
            <span><?php echo __('Wishlist'); ?></span>
        </a>
    </div>
</div>
<!-- jquery -->

<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
       
        $(document).ready( function() {
            $("#login_click").click(function(){
            if($(".login_mobi").css('display')=='none')
                 $(".login_mobi").css('display','block')
            else
                $(".login_mobi").css('display','none')
            });
         });

    });
</script>

