<?php
/** @var \Magetop\Helloworld\Block\Widget\Posts $block*/
?>

<?php if($block->getData('posts_title')): ?>
	<h2 class='posts_title'><?php echo $block->getData('posts_title'); ?></h2>
	<p>This is sample widget. Perform your code here.</p><br/>
<?php endif; ?>
<h1 style="color: red;">Template List</h1>
<?php if($block->getData('description')): ?>
	<p class='description'><?php echo $block->getData('description'); ?></p>
<?php endif; ?>

<?php
	$posts=$block->getCollection();
	$postSelects=explode (',', $block->getSelection('data_options'));
?>

<div class="blog-widget-title"><a></a></div>
<div class="post-list-container mpcss" id="mpblog-list-container">
    <div class="widget-title">
        <a href="<?= $block->escapeUrl($block->getBlogUrl('')) ?>"><?= $block->escapeHtml($block->getTitle()) ?></a>
    </div>
    <div class="row">
        <?php foreach ($posts as $post) : ?>
			<?php foreach ($postSelects as $postSelect) : ?>
				<?php 
					$count=0;
					if($block->escapeUrl($post->getId())==$postSelect) {?>
					<div class="post-list-item" style="margin-left: 5px">
						<div class="post-item-wraper">
							<?php if ($post->getImage()) : ?>
								<div class="post-image">
									<a href="<?= $block->escapeUrl($post->getUrl()) ?>">
										<img class="img-responsive" style="height: 220px"
											src="<?= $block->escapeUrl($block->resizeImage($post->getImage(), '400x')) ?>"
											alt="<?= $block->escapeHtml($post->getName()); ?>"/>
									</a>
								</div>
							<?php endif; ?>
							<div class="post-info-wraper">
								<h2 class="mp-post-title" style="font-size: 22px">
									<a class="post-link-title" title="<?= $block->escapeHtmlAttr($post->getName()) ?>"
									href="<?= $block->escapeUrl($post->getUrl()) ?>">
										<?= $block->escapeHtml($post->getName()) ?>
									</a>
								</h2>
								<div class="mp-post-info">
									<?= /** @noEscape */ $block->getPostInfo($post) ?>
								</div>
								<div class="post-short-description">
									<p><?= /** @noEscape */ $post->getShortDescription() ?></p>
								</div>
								<div class="mp-clearfix"></div>
								<div class="mp-post-meta-info mp-alignright">
									<div class="actions">
										<a class="mp-read-more" href="<?= $block->escapeUrl($post->getUrl()) ?>"
										title="<?= $block->escapeHtmlAttr(__('Read More')) ?>">
											<?= $block->escapeHtml(__('Read more')) ?>
										</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				<?php 
					$count+=1;
				}?>
			<?php endforeach; ?>
			<?php if($count>$block->getData('post_count')){
				break;
			} ?>
        <?php endforeach; ?>
    </div>
</div>
